import pygame

pygame.font.init()

class Config:
    # SCREEN
    WIDTH = 1000
    HEIGHT = 500

    # GAME LOOP
    RUN = False
    FPS = 60
    
    # SPACESHIP
    SPACESHIP_SCALE = WIDTH // 12, HEIGHT // 8

    RED_SPACESHIP_POSITION = (WIDTH, HEIGHT)
    RED_SPACESHIP_POSITION = (RED_SPACESHIP_POSITION[0] - SPACESHIP_SCALE[0], RED_SPACESHIP_POSITION[1] - SPACESHIP_SCALE[1])
    RED_SPACESHIP_POSITION = ((RED_SPACESHIP_POSITION[0] // 2) / 2, RED_SPACESHIP_POSITION[1] // 2)
    
    RED_HIT = pygame.USEREVENT + 1

    RED_HEALTH = 10

    YELLOW_SPACESHIP_POSITION = (WIDTH, HEIGHT)
    YELLOW_SPACESHIP_POSITION = (YELLOW_SPACESHIP_POSITION[0] - SPACESHIP_SCALE[0], YELLOW_SPACESHIP_POSITION[1] - SPACESHIP_SCALE[1])
    YELLOW_SPACESHIP_POSITION = ((YELLOW_SPACESHIP_POSITION[0] // 2) // 2, YELLOW_SPACESHIP_POSITION[1] // 2)
    YELLOW_SPACESHIP_POSITION = (YELLOW_SPACESHIP_POSITION[0] * 3, YELLOW_SPACESHIP_POSITION[1])

    YELLOW_HIT = pygame.USEREVENT + 2
    
    YELLOW_HEALTH = 10

    # SPACESHIP BULLETS
    RED_BULLETS = []
    YELLOW_BULLETS = []

    # MIDDLE BORDER
    MIDDLE_BORDER_SCALE = (10, HEIGHT)
    
    MIDDLE_BORDER_POSITION = (WIDTH // 2, 0)
    MIDDLE_BORDER_POSITION = (MIDDLE_BORDER_POSITION[0] - MIDDLE_BORDER_SCALE[0], MIDDLE_BORDER_POSITION[1])

    # FONTS
    HEALTH_FONT = pygame.font.SysFont("comicsans", 40, True)
    WINNER_FONT = pygame.font.SysFont("comicsans", 120, True)
